### ISSUE TITLE
Missing "END LIBRARY" Statement in Cell LEF files.

### ISSUE THREAD

**Issue by acasper45** [google/skywater-pdk#104] opened 2020-07-19 19:09 UTC
The current LEF files generated for the Skywater PDK cells lack an "END LIBRARY" statement at the end of the file. Without this statement the OpenRoad LEF parser complains with an error message 

```Error: ERROR (LEFPARS-1002): Incomplete lef file.``` 

Adding "END LIBRARY" to the last line of the LEF file eliminates this error and the cells are imported without issue.

Unless the "END LIBRARY" was purposefully removed seems like it would be useful to add, even if we do ultimately end up merging all the LEFs into a single file (e.g. [issue 52](https://github.com/google/skywater-pdk/issues/51).)

**Comment by mithro** [comment] 2020-07-19 19:33
@acasper45 Does there need to be some type of "start library"?

**Comment by acasper45** [comment] 2020-07-19 19:42
I was wondering the same thing but I don't think there is need for a "start library" type statement. I'm no LEF file expert by any means but looking at existing examples and [this reference](http://www.ispd.cc/contests/18/lefdefref.pdf) it seems an "END LIBRARY" is all thats required.

**Comment by RTimothyEdwards** [comment] 2020-07-20 02:14
@mithro :  This is probably caused by Magic, which does not put "END LIBRARY" at the end of single macro output files.  Note that this is because _there is no documented use of the statement "END LIBRARY" in the LEF/DEF spec_!  Therefore I maintain that the commercial tools are in error.  However, since according to the above, it appears that "END LIBRARY" is what commercial tools want to see at the end of every LEF file (in spite of the complete uselessness of such a statement), I have added it to the output that Magic generates for single macros.

**Comment by RTimothyEdwards** [comment] 2020-07-20 02:16
Also:  No, there is no "LIBRARY" statement corresponding to "END LIBRARY", although that is the way "END" is used in _every single other LEF/DEF "END" statement_.  Once again, LEF/DEF spec fails to make internally consistent sense.

**Comment by mithro** [comment] 2020-07-20 16:05
I will push standard cells with this updated.

**Comment by mithro** [comment] 2020-07-21 20:42
This is now fixed!

**Closed** 2020-07-21 20:42 UTC
Labels: files-layout-lef, files-layout-lef-magic, in-progress, lib-sky130_fd_sc_hd, lib-sky130_fd_sc_hdll, lib-sky130_fd_sc_hs, lib-sky130_fd_sc_hvl, lib-sky130_fd_sc_lp, lib-sky130_fd_sc_ls, lib-sky130_fd_sc_ms
